config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users
  resources :availabilities do
  resources :requests
  end
     get 'pages/dashboard'
  get "pages/pending"

  root to: "pages#index"
  resources :conversations do
  resources :messages
  end
  get 'layouts/application'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/pages/:page" => "pages#schedules"
  get "/pages/:page" => "pages#shift-exchange"
  get "/pages/:page" => "pages#messages"
  get "/pages/:page" => "pages#new-staff"
  get "/pages/:page" => "pages#schedules"
  get "/pages/:page" => "pages#about"
  

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :availability
  belongs_to :user
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
	before_action :set_availability, only: [:show, :new, :edit, :create, :update, :destroy]
  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @request.availability_id = @availability.id
		@availability.update(:status => "Pending Swap")
		@availability.update(:title => @request.user.email)
    @request.user.email = ''
    
    respond_to do |format|
      if @request.save
        format.html { redirect_to @availability, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @availability }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @availability, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @availability }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end
  
  def set_availability
	@availability = Availability.find(params[:availability_id])
end 

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:comment, :availability_id, :user_id)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<div class="container">
  <%= form_for [@availability, @request] do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h4>
  Currently assigned: <%= @availability.title %></h4>
  <br>
      <h5>
        Who do you want to take this shift? <%= form.select :user_id, User.pluck(:email, :id) %>
  </h5>
  <div class="field">
    <%= form.label :comment, "Why are you requesting this shift off?" %>
    <%= form.text_area :comment, class: 'form-control' %>
  </div>
<br>
  <div class="actions">
    <%= form.submit "Request Shift Swap", class: 'w3-btn btn btn-round w3-green' %>
  </div>
<% end %>
  
</div>

<script>
function myFunction() {
    var input, filter, ul, li, a, i;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    ul = document.getElementById("myUL");
    li = ul.getElementsByTagName("li");
    for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("a")[0];
        if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";
        }
    }
}
</script>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.comment %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @request.comment %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>