config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users
  resources :availabilities do
  resources :requests
  end
     get 'pages/dashboard'
  get "pages/pending"

  root to: "pages#index"
  resources :conversations do
  resources :messages
  end
  get 'layouts/application'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/pages/:page" => "pages#schedules"
  get "/pages/:page" => "pages#shift-exchange"
  get "/pages/:page" => "pages#messages"
  get "/pages/:page" => "pages#new-staff"
  get "/pages/:page" => "pages#schedules"
  get "/pages/:page" => "pages#about"
  

end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :user
  has_many :requests

end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :set_availability, only: [:show, :edit, :update, :destroy]
   before_action :user_is_current_user, only: [:show, :edit, :update, :destroy]
  # GET /availabilities
  # GET /availabilities.json
  def index
    @availabilities = Availability.all
  end

  # GET /availabilities/1
  # GET /availabilities/1.json
  def show
    @requests = @availability.requests
  end

  # GET /availabilities/new
  def new
    @availability = Availability.new
    @availability.user_id = current_user.id
  end

  # GET /availabilities/1/edit
  def edit
    
  end

  # POST /availabilities
  # POST /availabilities.json
  def create
    @availability = Availability.new(availability_params)
    @availability.user_id = current_user.id
    @availability.status = 'Available'
    @availability.title = current_user.email
    respond_to do |format|
      if @availability.save
        format.html { redirect_to @availability, notice: 'Availability was successfully created.' }
        format.json { render :show, status: :created, location: @availability }
      else
        format.html { render :new }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /availabilities/1
  # PATCH/PUT /availabilities/1.json
  def update
    if current_user.admin?
      @availability.update(:status => "Confirmed")
      if @availability.title?
        @availability.user.update(:email => @availability.title)
      end 
    end
    respond_to do |format|
      if @availability.update(availability_params)
        format.html { redirect_to @availability, notice: 'Availability was successfully updated.' }
        format.json { render :show, status: :ok, location: @availability }
      else
        format.html { render :edit }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /availabilities/1
  # DELETE /availabilities/1.json
  def destroy
    @availability.destroy
    respond_to do |format|
      format.html { redirect_to availabilities_url, notice: 'Availability was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_availability
      @availability = Availability.find(params[:id])
    end
    def user_is_current_user
      unless current_user == @availability.user or current_user.admin
        redirect_to(availabilities_url, alert: "You cannot edit view this") and return
      end
    end
     

    # Never trust parameters from the scary internet, only allow the white list through.
    def availability_params
      params.require(:availability).permit(:start_time, :end_time, :assigned, :user_id, :test_name, :start, :end, :title, :request, :status)
    end
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/views/availabilities/_form.html.erb
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  <%= form_with(model: availability, local: true) do |form| %>
  <% if availability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(availability.errors.count, "error") %> prohibited this availability from being saved:</h2>

      <ul>
      <% availability.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      <div class="w3-card-4" style="width: 90%; text-align: left;">
        <header class="w3-container details-heading">
          <% if current_user.try(:admin) %> <!-- this is for manager to assign the availability to a user-->
                <p class="white">
                  Current Assigned: <%= @availability.user.email %>
            </p>
            <p class="white">Requested Employee: <%= @availability.title %></p>
          <% else %>
                <%= form.hidden_field :title, value: @availability.user.email, style: "display: hidden" %> <!-- this is for user to automatically be assigned to an availbaility.-->
          <% end %>      
        </header>
      <div class="w3-container" style="padding-top: 3%;">
        <div class="field white">
          <%= form.label :start_time %>
          <%= form.datetime_select :start_time %>
        </div>

        <div class="field white">
          <%= form.label :end_time %>
          <%= form.datetime_select :end_time %>
        </div>
      </div>
        <footer class="w3-container" style="padding-bottom: 10px;">
        </footer>
      </div>
<br>


  <div class="actions">
    <%= form.submit 'Submit', :class => 'w3-btn w3-round accept-btn' %>
  </div>
<% end %>
<script type="text/javascript">
  $('.datetimepicker').datetimepicker({
    format: "YYYY-MM-DD"
  });
  </script>

app/views/availabilities/edit.html.erb
<div class="container" style="padding-top: 5%;">
  <div style="padding: 0 25% 0 25%;">
    <h2 class="w3-center small-border-bottom">EDIT SHIFT</h2><br>
  </div>
<%= render 'form', availability: @availability %>

<%= link_to 'Back', availabilities_path, :class => "w3-btn w3-round decline-btn", :style => "margin-top: 1%;" %>
</div>

app/views/availabilities/index.html.erb
<html>
<body style="height: auto;">
<% if user_signed_in? %>
<p id="notice"></p>
<div class="container" style="padding-top: 5%;">
  <div class="w3-row">
  <!--
      <div class="w3-col w3-left" style="width: 40%; padding: 0 8% 0 0%; margin-top: 15%;">
        <div class="w3-card-4" style="height: 15%;">
          <header class="w3-container legend-card">
            <h3 class="w3-center">Legend</h3>
          </header>
          <div class="w3-container" style="background-color: #F8F8F8;">
            <div class="row">
              <div class="w3-col s3 w3-green w3-panel w3-card"><p>w3-card</p></div>
              <div class="w3-col s3 w3-dark-grey w3-panel w3-card"><p>w3-card</p></div>
            </div>
          </div>
        </div><br>
        <div class="w3-card-4" style="height: 15%;">
          <header class="w3-container notification-card">
            <h3 class="w3-center">Notifications</h3>
          </header>
          <div class="container" style="background-color: #F8F8F8;">
            <div style="background-color: #DEDEDE; height: 100%; margin: 5% 0 5% 0;">
              <p class="w3-right" style="margin-right: 5px;">x</p><br>
              <p style="margin-left: 5px;">Coworker has requested their shift be taken on Oct. 2nd at 5:00pm. Would you like to accept?</p>
              <div class="w3-center">
                <button class="w3-button w3-round-large accept-btn" style="width: 40%;">Accept</button>
                <button class="w3-round-large decline-btn" style="width: 40%;">Decline</button>
                <p></p>
              </div>
            </div>
          </div>
        </div>
    </div>
    -->
    <div class="w3-col" style="width: 100%">
      <div style="padding: 0px 25% 0px 25%;"><h2 class="w3-center small-border-bottom">TECM LAB SHIFTS</h2><br></div>
<%= month_calendar(attribute: :start_time, end_attribute: :end_time, events: @availabilities) do |date, availabilities| %>
  <%= date.to_formatted_s(:short) %>
  <% availabilities.each do |availability| %>
    <% if availability.status == 'Confirmed' or availability.status == 'Confirmed Swap' %>     
     <%= link_to availability do %>
      <div id="confirmed-tag"></div>
      <div class="confirmed">
        <%= availability.title %><br>
        <%= availability.start_time.strftime("%l:%M %p") %> - <%= availability.end_time.strftime("%l:%M %p") %>
      </div>
      <% end %>
       <% elsif availability.status == 'Pending' or availability.status == 'Pending Swap' %>   
        <%= link_to availability do %>
      <div id="pending-tag"></div>
          <div class="pending">
            <%= availability.title %><br>
            <%= availability.start_time.strftime("%l:%M %p") %> - <%= availability.end_time.strftime("%l:%M %p") %>
          </div>
       <% end %>
      <% end %>  
<% end %>
<% end %>
</div>
<% end %>
</body>
</html>
<script>

function move() {
    var elem = document.getElementById("hours-meter"); 
    var width = 1;
    var id = setInterval(frame, 10);
    function frame() {
        if (width >= 100) {
            clearInterval(id);
        } else {
            width++; 
            elem.style.width = width + '%'; 
        }
    }
}
  
$('#calendar').fullCalendar({ 
   events: '/availabilities.json'
  
});
</script>

app/views/availabilities/new.html.erb
<div class="container" style="padding-top: 5%;">
  <div style="padding: 0 25% 0 25%;">
    <h2 class="w3-center small-border-bottom">ADD AVAILABILITY</h2><br>
  </div>
<%= render 'form', availability: @availability %>

<%= link_to 'Back', availabilities_path, :class => "w3-btn w3-round decline-btn", :style => "margin-top: 1%;" %>

app/views/availabilities/show.html.erb
<html>
<body>

<div class="w3-container" style="margin-top: 5%;">
    <div class="w3-col s6 w3-left">
      <div class="w3-center">
        <h3 class="small-border-bottom" style="text-transform: uppercase;"><%= @availability.user.email %>'s Shift Details</h3><br>
      </div>
      <div class="w3-card-4 w3-center" style="width: 90%; text-align: left;">
        <header class="w3-container details-heading">
         <h4>Shift Status: <%= @availability.status %></h4>       
        </header>
      <div class="w3-container">
      <p>
        <strong>Start time:</strong>
        <span style="color: #fff;"><%= @availability.start_time.strftime("%B %d, %Y, %l:%M %p") %></span>
      </p>
      <p>
        <strong>End time:</strong>
        <span style="color: #fff;"><%= @availability.end_time.strftime("%B %d, %Y, %l:%M %p") %></span>
      </p>
      </div>
        <footer class="w3-container" style="padding-bottom: 10px;">
            <% unless current_user.try(:admin) %>
                <%= link_to 'Submit', new_availability_request_path(@availability), class: 'w3-button w3-round accept-btn' %>
            <% else %>
           <%= link_to 'Submit', edit_availability_path(@availability), class: 'w3-button w3-round accept-btn' %>

            <% end %> 
        </footer>
      </div>
     </div><!--/col-md-7-->
  
   <div class="w3-col s6 w3-right">
      <div class="w3-center">
        <h3 class="small-border-bottom" style="text-transform: uppercase;"><%= @availability.user.email %>'s Active Requests</h3><br>
      </div><br>
     <% if @request.blank? %>
          <% @requests.each do |request| %>
          <table cellpadding="0" cellspacing="0" class="pending-table noborders table" style="margin: 0; padding: 0;">
            <thead>
              <th>Requested Person</th>
              <th>Shift Swap Request Details</th>
              <th>Person who is taking your shift</th>
              <th>Status</th>
            </thead>
            <tbody>
              <tr class="small-border-bottom">
              <td>
               <%= request.user.email %>
              </td>
                <td><%= request.comment %></td>
               <% if @availability.status == 'Confirmed Swap' %>
                <td><%= @availability.title %></td>
                <td><%= @availability.status %></td>


                <% else %>
                <td>Pending Manager Approval</td>
                <td>Pending Manager Approval</td>


                <% end %>
                
              </tr>
            </tbody>
          </table>
          
          <% end %>
        <% else %>
     <h1>
       You do not have any active shift requests. YOu have to work!
     </h1>
    <% end %>
<br>
   </div>
</div><!--/container-->
</body>
</html>