config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users
  resources :availabilities do
  resources :requests
  end
     get 'pages/dashboard'
  get "pages/pending"

  root to: "pages#index"
  resources :conversations do
  resources :messages
  end
  get 'layouts/application'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/pages/:page" => "pages#schedules"
  get "/pages/:page" => "pages#shift-exchange"
  get "/pages/:page" => "pages#messages"
  get "/pages/:page" => "pages#new-staff"
  get "/pages/:page" => "pages#schedules"
  get "/pages/:page" => "pages#about"
  

end

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <div class="row landing-nav-dashboard">
    <div class="w3-col" style="width: 55%;">
        <%= link_to "My Shift", pages_dashboard_path,  class: "w3-bar-item w3-button nav-padding-left-small w3-mobile" %>
        <%= link_to "Messages", conversations_path, class: "w3-bar-item w3-button nav-padding-left-small w3-mobile" %>
        <a href="/availabilities" class="w3-bar-item w3-button w3-mobile nav-padding-left-small">Calendar</a>
      <% if current_user.try(:admin) %>
        <%= link_to "Pending Requests", pages_pending_path, class:'w3-bar-item w3-button w3-mobile nav-padding-left-small' %>
      <% end %>
    </div>
    <div class="w3-col" style="width: 45%;">
      <div class="w3-dropdown-hover no-background w3-text-white w3-right w3-mobile">
        <div class="w3-left nav-padding-left w3-mobile menu-show arvo-text"><p>Hello, <%= current_user.email %>!</p></button></i>
        <div class="w3-dropdown-content w3-bar-block w3-card-4" style="font-size: 16px;">
          <a href="#" class="w3-bar-item w3-button w3-right w3-mobile">My Profile</a>
          <a href="/pages/settings" class="w3-bar-item w3-button w3-mobile">Settings</a>
          <a href="#" class="w3-bar-item w3-button w3-mobile">Privacy</a>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "w3-bar-item w3-button w3-mobile" %>
        </div>
      </div>
    </div>
  </div>
</div>
<% else %>
<div class="row landing-nav">
   <div class="w3-col s9">
     <a href="/" class="w3-bar-item w3-button nav-padding-left logo-title w3-mobile" style="font-size: 36px;">Shwap</a>
     <a href="#" class="w3-bar-item w3-button nav-padding-left w3-mobile">Contact</a>
     <a href="#" class="w3-bar-item w3-button nav-padding-left w3-mobile">About</a>
     <a href="#" class="w3-bar-item w3-button nav-padding-left w3-mobile">Our Partners</a>
   </div>
   <div class="w3-col s3">
     <a data-toggle="modal" data-target="#logInModal" class="w3-bar-item w3-button w3-left nav-padding-right w3-mobile">Login</a> 
     <a data-toggle="modal" data-target="#signUpModal" class="w3-bar-item w3-button w3-left nav-padding-right get-started w3-mobile">Sign Up</a> 
    </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shwap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/proza-libre" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Sarina" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/proza-libre" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Share" rel="stylesheet">
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/all.css' integrity='sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU' crossorigin='anonymous'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
        <%= render 'layouts/navbar' %>


    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <a href="#" data-dismiss="alert" class="close">×</a>
          <ul>
            <li>
              <%= value %>
            </li>
          </ul>
        </div>
    <% end %>
      <%= yield %>
    <%= render partial: 'devise/registrations/new' %>
    <%= render partial: 'devise/sessions/new' %>
</body>
</html>

app/views/layouts/dashboard.html.erb
<p id="notice"><%= notice %></p>

<h1><%= current_user.email %>'s Availabilities</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>Assigned</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @availabilities.each do |availability| %>
      <tr>
        <td><%= availability.start_time %></td>
        <td><%= availability.end_time %></td>
        <td><%= availability.assigned %></td>
        <td><%= link_to 'Show', availability %></td>
        <td><%= link_to 'Edit', edit_availability_path(availability) %></td>
        <td><%= link_to 'Destroy', availability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Availability', new_availability_path %>